# Generated by Django 3.0.8 on 2020-07-29 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200730_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 30, 1, 38, 7, 139109), verbose_name='date published'),
        ),
    ]
